LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE =
LOCAL_MODULE = YYDRobotXYAR
LOCAL_MODULE_CLASS = APPS
LOCAL_MODULE_PATH = $(TARGET_OUT)/vendor/operator/app
LOCAL_MODULE_RELATIVE_PATH =
LOCAL_MODULE_SUFFIX = .apk
LOCAL_CERTIFICATE = PRESIGNED
LOCAL_SRC_FILES := YYDRobotXYAR.apk
include $(BUILD_PREBUILT)
